# **Numpy_Pandas**

# **Bài 1**

In [8]:
import numpy as np
import pandas as pd
# Tạo mảng 3x3 ngẫu nhiên từ 0 đến 20
arr1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng bài 1:\n", arr1)

# Kiểm tra xem tất cả các phần tử có khác 0 không
# np.all() trả về True nếu tất cả điều kiện đều đúng
all_non_zero = np.all(arr1 != 0)
print("Tất cả các phần tử đều khác 0:", all_non_zero)

Mảng bài 1:
 [[17  7 10]
 [ 2 20  9]
 [ 9 18  9]]
Tất cả các phần tử đều khác 0: True


# **Bài 2**

In [45]:
# Tạo mảng 3x3 ngẫu nhiên từ 0 đến 20
arr2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng bài 2:\n", arr2)

# Kiểm tra xem có bất kỳ phần tử nào khác 0 không
# np.any() trả về True nếu có ít nhất 1 điều kiện đúng
any_non_zero = np.any(arr2 != 0)
print("Có tồn tại phần tử khác 0:", any_non_zero)

Mảng bài 2:
 [[19  0 10]
 [11 11  9]
 [17  8  8]]
Có tồn tại phần tử khác 0: True


# **Bài 3**

In [46]:
# --- So sánh mảng 1 chiều ---
x1 = np.array([10, 20, 30])
y1 = np.array([20, 20, 10])

print("So sánh mảng 1 chiều:")
print("x1 > y1 (greater):", np.greater(x1, y1))
print("x1 >= y1 (greater_equal):", np.greater_equal(x1, y1))
print("x1 < y1 (less):", np.less(x1, y1))
print("x1 <= y1 (less_equal):", np.less_equal(x1, y1))

# --- So sánh mảng 2 chiều ---
x2 = np.array([[1, 5], [9, 12]])
y2 = np.array([[2, 4], [9, 15]])

print("\nSo sánh mảng 2 chiều:")
print("x2 > y2:\n", np.greater(x2, y2))

So sánh mảng 1 chiều:
x1 > y1 (greater): [False False  True]
x1 >= y1 (greater_equal): [False  True  True]
x1 < y1 (less): [ True False False]
x1 <= y1 (less_equal): [ True  True False]

So sánh mảng 2 chiều:
x2 > y2:
 [[False  True]
 [False False]]


# **Bài 4**

In [47]:
# Tạo các mảng con
arr_ones = np.ones(10)
arr_zeros = np.zeros(10)
arr_fives = np.full(10, 5) # Hoặc dùng np.ones(10) * 5

# Nối các mảng lại với nhau
arr4 = np.concatenate((arr_ones, arr_zeros, arr_fives))
print("Mảng gồm 10 số 1, 10 số 0, 10 số 5:\n", arr4)

Mảng gồm 10 số 1, 10 số 0, 10 số 5:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


# **Bài 5**

In [48]:
# Sử dụng arange(start, stop, step)
# stop là 71 để bao gồm cả số 70
arr5 = np.arange(30, 71, 2)
print("Mảng số nguyên chẵn từ 30 đến 70:\n", arr5)

Mảng số nguyên chẵn từ 30 đến 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# **Bài 6**

In [49]:
# np.identity tạo ma trận vuông với đường chéo chính là 1
arr6 = np.identity(3)
print("Ma trận đơn vị 3x3:\n", arr6)

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Bài 7**

In [50]:
# Tạo mảng 10 số nguyên ngẫu nhiên trong khoảng [15, 55]
arr7 = np.random.randint(15, 56, size=10)
print("Mảng ban đầu:\n", arr7)

# Cắt mảng (slicing) từ index 1 đến index kế cuối (-1)
print("Mảng trừ phần tử đầu và cuối:\n", arr7[1:-1])

Mảng ban đầu:
 [45 29 51 41 24 55 37 54 33 44]
Mảng trừ phần tử đầu và cuối:
 [29 51 41 24 55 37 54 33]


# **Bài 8**

In [51]:
arr8 = np.random.randint(0, 21, size=20)
print("Mảng ban đầu:\n", arr8)

# Dùng indexing điều kiện (boolean indexing) để tìm và đổi dấu
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1
print("Mảng sau khi đổi dấu các số từ 9 đến 15:\n", arr8)

Mảng ban đầu:
 [11 20 13  0  7  5  8 15  9 19 14 16 11 18  8  9 12  4  4 12]
Mảng sau khi đổi dấu các số từ 9 đến 15:
 [-11  20 -13   0   7   5   8 -15  -9  19 -14  16 -11  18   8  -9 -12   4
   4 -12]


# **Bài 9**

In [52]:
# Hàm randint có mức trần (stop) không bao gồm giá trị đó, nên ta dùng 22
arr9 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", arr9)

Ma trận 3x4:
 [[16 17 15 19]
 [12 13 13 15]
 [19 18 17 21]]


# **Bài 10**

In [53]:
# Bước 1: Tạo ma trận toàn số 1
arr10 = np.ones((10, 10))

# Bước 2: Sửa các phần tử bên trong thành số 0 (chừa lại hàng/cột đầu và cuối)
arr10[1:-1, 1:-1] = 0
print("Ma trận 10x10:\n", arr10)

Ma trận 10x10:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# **Bài 11**

In [54]:
# Hàm np.diag sẽ tự động điền các giá trị vào đường chéo chính của ma trận vuông
arr11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", arr11)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# **Bài 12**

In [55]:
arr12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3x3x3 ban đầu:\n", arr12)

# Trong mảng 3D: axis=0 là chiều sâu, axis=1 là cột, axis=2 là dòng
sum_cols = np.sum(arr12, axis=1)
print("\nTổng theo mỗi cột:\n", sum_cols)

sum_rows = np.sum(arr12, axis=2)
print("\nTổng theo mỗi dòng:\n", sum_rows)

Mảng 3x3x3 ban đầu:
 [[[4 2 8]
  [2 8 1]
  [1 1 2]]

 [[2 4 1]
  [6 8 5]
  [1 8 9]]

 [[4 5 3]
  [5 7 5]
  [4 5 2]]]

Tổng theo mỗi cột:
 [[ 7 11 11]
 [ 9 20 15]
 [13 17 10]]

Tổng theo mỗi dòng:
 [[14 11  4]
 [ 7 19 18]
 [12 17 11]]


# **Bài 13**

In [59]:
v1 = np.random.randint(1, 10, size=10)
v2 = np.random.randint(1, 10, size=10)
print("Vector 1:", v1)
print("Vector 2:", v2)

# Tính tích vô hướng
inner_product = np.dot(v1, v2)
print("Tích vô hướng (np.dot):", inner_product)

Vector 1: [3 4 5 8 4 7 2 3 4 2]
Vector 2: [2 2 8 7 5 7 9 8 2 6]
Tích vô hướng (np.dot): 241


# **Bài 14**

In [58]:
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)
print("Ma trận A:\n", A)
print("Vector y:", y)

# Nhờ cơ chế Broadcasting của Numpy, ta chỉ cần làm phép cộng trực tiếp
result14 = A + y
print("\nMa trận A sau khi cộng vector y vào từng dòng:\n", result14)

Ma trận A:
 [[1 3 5]
 [1 1 3]
 [5 2 8]
 [5 6 5]]
Vector y: [4 2 5]

Ma trận A sau khi cộng vector y vào từng dòng:
 [[ 5  5 10]
 [ 5  3  8]
 [ 9  4 13]
 [ 9  8 10]]


# **Bài 15**

In [60]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("--- Cộng ---\n", s1 + s2)
print("--- Trừ ---\n", s1 - s2)
print("--- Nhân ---\n", s1 * s2)
print("--- Chia ---\n", s1 / s2)

--- Cộng ---
 0     3
1     7
2    11
3    15
4    20
dtype: int64
--- Trừ ---
 0    1
1    1
2    1
3    1
4    0
dtype: int64
--- Nhân ---
 0      2
1     12
2     30
3     56
4    100
dtype: int64
--- Chia ---
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


# **Bài 16**

In [61]:
# Tạo DataFrame giống hình mẫu
data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}
df16 = pd.DataFrame(data)

# Lấy tất cả các dòng (:) của cột đầu tiên (index 0)
first_col_series = df16.iloc[:, 0]
print("Cột thứ nhất dưới dạng một Series:\n", first_col_series)

Cột thứ nhất dưới dạng một Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


# **Bài 17**

In [41]:
# Tạo DataFrame ngẫu nhiên
df17 = pd.DataFrame(np.random.randint(1, 50, size=(4, 3)), columns=['Cột 1', 'Cột 2', 'Cột 3'])
print("DataFrame ban đầu:\n", df17)

# Sắp xếp tăng dần theo 'Cột 1'
df17_sorted = df17.sort_values(by='Cột 1')
print("\nDataFrame sau khi sắp xếp theo 'Cột 1':\n", df17_sorted)

DataFrame ban đầu:
    Cột 1  Cột 2  Cột 3
0     26     18     41
1     13     36     25
2     46     45      3
3     40      2     35

DataFrame sau khi sắp xếp theo 'Cột 1':
    Cột 1  Cột 2  Cột 3
1     13     36     25
0     26     18     41
3     40      2     35
2     46     45      3


# **Bài 18**

In [23]:
import pandas as pd

# Khởi tạo Series với index ban đầu
s = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Chuỗi dữ liệu gốc:\n", s)

# Sử dụng reindex để sắp xếp lại thứ tự index
s_reindexed = s.reindex(['B', 'A', 'C', 'D', 'E'])
print("\nChuỗi dữ liệu sau khi thay đổi thứ tự của chỉ số:\n", s_reindexed)

Chuỗi dữ liệu gốc:
 A    1
B    2
C    3
D    4
E    5
dtype: int64

Chuỗi dữ liệu sau khi thay đổi thứ tự của chỉ số:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


# **Bài 19**

In [62]:
# Tạo dữ liệu giống như mẫu
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:\n", sr1)
print("\nsr2:\n", sr2)

# sr1.isin(sr2) trả về True nếu phần tử của sr1 nằm trong sr2
# Thêm dấu ~ phía trước để lấy phủ định (nghĩa là lấy các phần tử KHÔNG nằm trong sr2)
result = sr1[~sr1.isin(sr2)]
print("\nCác mục của sr1 không có trong sr2:\n", result)

sr1:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Các mục của sr1 không có trong sr2:
 0    1
2    3
4    5
dtype: int64


# **Bài 20**

In [26]:
import numpy as np

# Tạo 2 Series ngẫu nhiên 20 phần tử, giá trị từ 1 đến 50
x = pd.Series(np.random.randint(1, 51, size=20))
y = pd.Series(np.random.randint(1, 51, size=20))

# Hội (Union): Lấy tất cả các phần tử của cả x và y (loại bỏ các giá trị trùng lặp)
union_result = pd.Series(np.union1d(x, y))
print("Hội (Union) của x và y:\n", union_result)

# Giao (Intersection): Lấy các phần tử chung xuất hiện ở cả x và y
intersect_result = pd.Series(np.intersect1d(x, y))
print("\nGiao (Intersection) của x và y:\n", intersect_result)


Hội (Union) của x và y:
 0      3
1      4
2      6
3      7
4      9
5     11
6     12
7     13
8     15
9     17
10    18
11    20
12    23
13    24
14    26
15    32
16    33
17    34
18    35
19    37
20    38
21    40
22    41
23    43
24    47
25    49
dtype: int64

Giao (Intersection) của x và y:
 0     3
1     7
2    11
3    13
4    17
5    26
dtype: int64


# **Bài 21**

In [29]:
import pandas as pd

# 1. Khởi tạo 2 Series x và y với dữ liệu bám sát hình mẫu
series_x = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
series_y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])

print("--- Series x ---")
print(series_x)
print("\n--- Series y ---")
print(series_y)

# 2. Thêm series y vào series x theo chiều dọc (Vertical)
# Sử dụng pd.concat() với tham số mặc định (axis=0) để nối dọc.
# Kết quả vẫn sẽ là một Series dài gấp đôi.
vertical_concat = pd.concat([series_x, series_y])
print("\n--- Thêm theo chiều dọc (Vertical) ---")
print(vertical_concat)

# 3. Thêm series y vào series x theo chiều ngang (Horizontal)
# Thêm tham số axis=1 để chỉ định nối theo cột (chiều ngang).
# Lúc này kết quả sẽ biến đổi thành một DataFrame có 2 cột (0 và 1) giống hệt hình mẫu.
horizontal_concat = pd.concat([series_x, series_y], axis=1)
print("\n--- Thêm theo chiều ngang (Horizontal) ---")
print(horizontal_concat)

--- Series x ---
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

--- Series y ---
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

--- Thêm theo chiều dọc (Vertical) ---
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

--- Thêm theo chiều ngang (Horizontal) ---
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


# **Bài 22**

In [39]:

# Khai báo dữ liệu theo đề bài
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Tạo DataFrame và gán index
df = pd.DataFrame(exam_data, index=labels)

print("Bài 22 - Dữ liệu DataFrame:\n")
print(df)

Bài 22 - Dữ liệu DataFrame:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# **Bài 23**

In [31]:
# Sử dụng hàm head() để lấy các dòng đầu tiên
print("Bài 23 - 3 dòng đầu tiên:\n")
print(df.head(3))

Bài 23 - 3 dòng đầu tiên:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


# **Bài 24**

In [32]:
# Truyền vào một list chứa tên các cột cần lấy
print("Bài 24 - Cột 'name' và 'score':\n")
print(df[['name', 'score']])

Bài 24 - Cột 'name' và 'score':

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


# **Bài 25**

In [33]:
# Lọc (boolean indexing) trên cột attempts
print("Bài 25 - Những dòng có attempts > 2:\n")
print(df[df['attempts'] > 2])

Bài 25 - Những dòng có attempts > 2:

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


# **Bài 26**

In [34]:
# Thuộc tính shape trả về một tuple (số_dòng, số_cột)
print("Bài 26 - Kích thước DataFrame:")
print("Tổng số dòng:", df.shape[0])
print("Tổng số cột:", df.shape[1])

Bài 26 - Kích thước DataFrame:
Tổng số dòng: 10
Tổng số cột: 4


# **Bài 27**

In [35]:
# Hàm isnull() kiểm tra xem giá trị có phải là NaN hay không
print("Bài 27 - Những dòng có score bị khuyết (NaN):\n")
print(df[df['score'].isnull()])

Bài 27 - Những dòng có score bị khuyết (NaN):

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


# **Bài 28**

In [36]:
# Hàm between(left, right) sẽ lấy các giá trị nằm trong đoạn [left, right]
print("Bài 28 - Những dòng có score từ 15 đến 20:\n")
print(df[df['score'].between(15, 20)])

Bài 28 - Những dòng có score từ 15 đến 20:

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


# **Bài 29**

In [37]:
# Sử dụng toán tử & (AND) để kết hợp 2 điều kiện. Lưu ý phải có dấu ngoặc tròn () bao quanh mỗi điều kiện.
print("Bài 29 - Dòng có attempt > 2 VÀ score từ 15 đến 20:\n")
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

Bài 29 - Dòng có attempt > 2 VÀ score từ 15 đến 20:

      name  score  attempts qualify
f  Michael   20.0         3     yes


# **Bài 30**

In [38]:
# Sử dụng loc[row_label, column_label] để định vị ô cần sửa và gán giá trị mới
df.loc['d', 'score'] = 19

print("Bài 30 - DataFrame sau khi cập nhật score của dòng 'd':\n")
print(df)

Bài 30 - DataFrame sau khi cập nhật score của dòng 'd':

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# **Tensorflow**

In [63]:
import tensorflow as tf
import numpy as np

# **Bài 1**

In [64]:
t1 = tf.zeros([2, 3])
print("Bài 1:\n", t1)

Bài 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# **Bài 2**

In [65]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.zeros_like(X) # Hoặc dùng tf.zeros(X.shape, dtype=X.dtype)
print("Bài 2:\n", t2)

Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


# **Bài 3**

In [66]:
t3 = tf.fill([3, 2], 5)
print("Bài 3:\n", t3)

Bài 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


# **Bài 4**

In [67]:
t4 = tf.linspace(5.0, 10.0, 50)
print("Bài 4:\n", t4)

Bài 4:
 tf.Tensor(
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ], shape=(50,), dtype=float32)


# **Bài 5**

In [68]:
t5 = tf.range(10, 101, delta=2)
print("Bài 5:\n", t5)

Bài 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


# **Bài 6**

In [69]:
t6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print("Bài 6:\n", t6)

Bài 6:
 tf.Tensor(
[[ 1.927023   0.4179146]
 [ 0.3053499  0.989282 ]
 [ 2.8923666 -0.5271063]], shape=(3, 2), dtype=float32)


# **Bài 7**

In [70]:
t7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print("Bài 7:\n", t7)

Bài 7:
 tf.Tensor(
[[0.47304535 0.22812033]
 [0.9579396  1.4389834 ]
 [1.8994982  0.53001237]], shape=(3, 2), dtype=float32)


# **Bài 8**

In [71]:
X_b8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X_b8)
print("Bài 8:\n", t8)

Bài 8:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# **Bài 9**

In [72]:
tensor_b9 = tf.random.normal((10, 10, 3))
t9 = tf.image.random_crop(tensor_b9, size=[5, 5, 3])
print("Bài 9 (shape sau khi cắt):\n", t9.shape)

Bài 9 (shape sau khi cắt):
 (5, 5, 3)


# **Bài 10**

In [73]:
x10 = tf.random.uniform([5])
y10 = tf.random.uniform([5])
# Dùng tf.where để trả về x+y nếu x<y, ngược lại trả về x-y
t10 = tf.where(x10 < y10, tf.add(x10, y10), tf.subtract(x10, y10))
print("Bài 10:\n", t10)

Bài 10:
 tf.Tensor([0.05804288 1.1507946  1.4509171  1.1858193  0.31394422], shape=(5,), dtype=float32)


# **Bài 11**

In [80]:
x11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y11 = tf.random.uniform([2, 3], minval=15, maxval=20)

# Lấy đường chéo của x và tạo lại ma trận chỉ giữ đường chéo
x_diag = tf.linalg.diag(tf.linalg.diag_part(x11))

# Do shape khác nhau, ta cần transpose y thành (3,2) để thực hiện phép cộng
t11 = tf.add(x_diag, tf.transpose(y11))
print("Bài 11:\n", t11)

Ma trận x11 ban đầu:
 [[7.1866174 7.24401  ]
 [5.6224756 8.117702 ]
 [7.98287   5.036175 ]]

Đường chéo của x11 (đã giữ đúng shape 3x2):
 [[7.1866174 0.       ]
 [0.        8.117702 ]
 [0.        0.       ]]

Ma trận y11 transpose:
 [[16.096874 15.22669 ]
 [15.484577 17.843689]
 [16.51901  15.814479]]

Kết quả Bài 11:
 [[23.283491 15.22669 ]
 [15.484577 25.961391]
 [16.51901  15.814479]]


# **Bài 12**

In [75]:
@tf.function
def math_graph_ops(x, y):
    return x+y, x-y, x*y, x/y

x12 = tf.random.uniform((3, 2, 2))
y12 = tf.random.uniform((3, 2, 2))
cong, tru, nhan, chia = math_graph_ops(x12, y12)
print("Bài 12 - Thực thi Graph thành công!")

Bài 12 - Thực thi Graph thành công!


# **Bài 13 - 14**

In [77]:
class BasicMathModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    # Bài 13: Tính tổng
    def sum_tensors(self, x, y):
        return tf.add(x, y)

    # Bài 14: Tính hiệu và tích
    def diff_and_prod(self, x, y):
        return tf.subtract(x, y), tf.multiply(x, y)

math_model = BasicMathModel(name="math_model")

# **Bài 15 - 16**

In [78]:
class GeometryModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    # Bài 15: P = (a + b) * 2
    def calc_perimeter(self, a, b):
        return tf.multiply(tf.add(a, b), 2.0)

    # Bài 16: S_xq = (a + b) * c * 2 | S_tp = (a * b) * 2 + S_xq
    def calc_surface_area(self, a, b, c):
        s_xq = tf.multiply(tf.multiply(tf.add(a, b), c), 2.0)
        s_day = tf.multiply(tf.multiply(a, b), 2.0)
        s_tp = tf.add(s_day, s_xq)
        return s_tp

# **Bài 17 - 18- 19**

In [79]:
class GeometryLogicProofModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

    # Bài 17: Kiểm tra cạnh bên hình thang song song (AD//BC <=> AD=BC và AB=CD)
    def prove_parallel_sides(self, AD, BC, AB, CD):
        cond1 = tf.equal(AD, BC)
        cond2 = tf.equal(AB, CD)
        return tf.logical_and(cond1, cond2)

    # Bài 18: Chứng minh hai cạnh đáy hình thang bằng nhau (AB=CD <=> AD=BC và AD//BC)
    def prove_equal_bases(self, AD, BC, is_AD_parallel_BC):
        cond1 = tf.equal(AD, BC)
        return tf.logical_and(cond1, is_AD_parallel_BC) # is_AD_parallel_BC là boolean

    # Bài 19: Tính chất đường trung bình tam giác (NA = NC)
    def prove_midpoint_N(self, AM, MB, is_MN_parallel_BC):
        # Nếu M là trung điểm AB (AM = MB) và MN // BC thì N sẽ là trung điểm AC (NA = NC)
        is_M_midpoint = tf.equal(AM, MB)
        return tf.logical_and(is_M_midpoint, is_MN_parallel_BC)